version: 2.1

jobs:
  quality: &test-template
    description: Code style
    docker:
      - image: python:3.10
    environment:
      PIP_PREFER_BINARY: true
      PIP_PROGRESS_BAR: "off"
      TOXENV: style
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox

  tests310:
    <<: *test-template
    description: Tests - Python 3.10
    docker:
      - image: python:3.10
    environment:
      TOXENV: tests310

  tests311:
    <<: *test-template
    description: Tests - Python 3.11
    docker:
      - image: python:3.11
    environment:
      TOXENV: tests311

  tests312:
    <<: *test-template
    description: Tests - Python 3.12
    docker:
      - image: python:3.12
    environment:
      TOXENV: tests312

  tests313:
    <<: *test-template
    description: Tests - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313

  tests313-fast:
    <<: *test-template
    description: Tests fast - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313-fast

  tests313-online:
    <<: *test-template
    description: Tests online - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313-online

  tests313-slow:
    <<: *test-template
    description: Tests slow - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313-slow

  tests313-images:
    <<: *test-template
    description: Tests images - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313-images
    steps:
      - checkout
      - run:
          name: Install OpenGL deps
          command: |
            apt-get update
            apt-get install -y --no-install-recommends \
              libgl1 libglx-mesa0 libgl1-mesa-dri libegl1-mesa-dev libgles2-mesa-dev libosmesa6 xvfb xauth
      - run: python -m pip install tox
      - run: xvfb-run -a tox

  tests313-coverage:
    <<: *test-template
    description: Tests coverage - Python 3.13
    docker:
      - image: python:3.13
    environment:
      TOXENV: tests313-coverage
    steps:
      - checkout
      - run: python -m pip install tox
      - run: tox
      - run: python -m pip install codecov && codecov

  tests314:
    <<: *test-template
    description: Tests - Python 3.14
    docker:
      - image: python:3.14
    environment:
      TOXENV: tests314


workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
      - tests311:
          requires:
            - quality
      - tests312:
          requires:
            - quality
      - tests313:
          requires:
            - quality
      - tests313-fast:
          requires:
            - quality
      - tests313-online:
          requires:
            - quality
      - tests313-slow:
          requires:
            - quality
      - tests313-images:
          requires:
            - quality
      - tests313-coverage:
          requires:
            - quality
      - tests314:
          requires:
            - quality
